name: front_end
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluentui_system_icons: ^1.1.241
  go_router: ^14.2.0
  step_progress_indicator: ^1.0.2
  flutter_hooks: ^0.20.5
  flutter_easyloading: ^3.0.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^8.2.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true